on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Build 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install libmpv 
      run: sudo apt-get install libmpv-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build 
      run: make pack 
    - name: Store binary file
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ./tuner
        
